;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__itof
	.import		__ftoi
	.import		__fsub
	.import		__ftostr
	.import		__fcmp
	.export		_ftoa
	.export		_ffloor

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ ftoa (__near__ unsigned char *, unsigned long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ftoa: near

.segment	"CODE"

	jsr     pusheax
	jsr     decsp2
	lda     #$00
	jsr     pusha
	ldy     #$21
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$29
	jsr     ldeaxysp
	jsr     __ftostr
	ldx     #$00
	lda     #$00
	ldy     #$23
	sta     (sp),y
	jmp     L002C
L002A:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L0033
	inx
L0033:	ldy     #$00
	jsr     ldauidx
	cmp     #$45
	jsr     booleq
	jeq     L0030
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	ldy     #$21
	sta     (sp),y
	jmp     L002B
L0030:	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
L002C:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L002F
	inx
L002F:	ldy     #$00
	jsr     ldauidx
	jne     L002A
L002B:	ldy     #$21
	ldx     #$00
	lda     (sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0037
	ldx     #$00
	lda     #$00
	ldy     #$22
	sta     (sp),y
	ldy     #$23
	sta     (sp),y
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L003F
	inx
L003F:	ldy     #$00
	jsr     ldauidx
	cmp     #$2D
	jsr     booleq
	jeq     L003C
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L0044
	inx
L0044:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L003C:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L004A
	inx
L004A:	ldy     #$00
	jsr     ldauidx
	cmp     #$20
	jsr     booleq
	jeq     L0047
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
L0047:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L004F
	inx
L004F:	ldy     #$00
	jsr     ldauidx
	cmp     #$2E
	jsr     booleq
	jeq     L004C
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$30
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$2E
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L004C:	jmp     L005B
L0059:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L0063
	inx
L0063:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L005B:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L005E
	inx
L005E:	ldy     #$00
	jsr     ldauidx
	jne     L0059
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	jmp     L0069
L0037:	ldx     #$00
	lda     #$00
	ldy     #$22
	sta     (sp),y
	ldy     #$23
	sta     (sp),y
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L0070
	inx
L0070:	ldy     #$00
	jsr     ldauidx
	cmp     #$2D
	jsr     booleq
	jeq     L006D
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L0075
	inx
L0075:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L006D:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L007B
	inx
L007B:	ldy     #$00
	jsr     ldauidx
	cmp     #$20
	jsr     booleq
	jeq     L0078
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
L0078:	ldy     #$21
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	clc
	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	ldy     #$30
	jsr     decaxy
	jsr     mulax10
	jsr     pushax
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	jsr     incax3
	clc
	adc     #$02
	bcc     L0084
	inx
	clc
L0084:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	ldy     #$30
	jsr     decaxy
	jsr     tosaddax
	ldx     #$00
	ldy     #$20
	sta     (sp),y
	ldy     #$21
	ldx     #$00
	lda     (sp),y
	jsr     incax1
	clc
	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	cmp     #$2B
	jsr     booleq
	jeq     L0085
	jmp     L008A
L0088:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L0098
	inx
L0098:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L008A:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L008D
	inx
L008D:	ldy     #$00
	jsr     ldauidx
	jeq     L008E
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L0090
	inx
L0090:	ldy     #$00
	jsr     ldauidx
	cmp     #$2E
	jsr     boolne
	jeq     L008E
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L0092
	inx
L0092:	ldy     #$00
	jsr     ldauidx
	cmp     #$45
	jsr     boolne
	jne     L008B
L008E:	ldx     #$00
	lda     #$00
	jeq     L0093
L008B:	ldx     #$00
	lda     #$01
L0093:	jne     L0088
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L009E
	inx
L009E:	ldy     #$00
	jsr     ldauidx
	cmp     #$45
	jsr     booleq
	jeq     L009B
	jmp     L00A1
L009F:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$30
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$20
	ldx     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	ldy     #$20
	sta     (sp),y
	pla
L00A1:	ldy     #$20
	lda     (sp),y
	jne     L009F
L009B:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L00AB
	inx
L00AB:	ldy     #$00
	jsr     ldauidx
	cmp     #$2E
	jsr     booleq
	jeq     L00BE
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	jmp     L00AF
L00AD:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L00B9
	inx
L00B9:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$20
	ldx     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	ldy     #$20
	sta     (sp),y
	pla
L00AF:	ldy     #$20
	lda     (sp),y
	jeq     L00B1
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L00B3
	inx
L00B3:	ldy     #$00
	jsr     ldauidx
	cmp     #$45
	jsr     boolne
	jne     L00B0
L00B1:	ldx     #$00
	lda     #$00
	jeq     L00B4
L00B0:	ldx     #$00
	lda     #$01
L00B4:	jne     L00AD
	jmp     L00BF
L00BD:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$30
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$20
	ldx     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	ldy     #$20
	sta     (sp),y
	pla
L00BF:	ldy     #$20
	lda     (sp),y
	jne     L00BD
L00BE:	jmp     L00DA
L0085:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$30
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$2E
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$20
	ldx     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	ldy     #$20
	sta     (sp),y
	pla
	jmp     L00D2
L00D0:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$30
	ldy     #$00
	jsr     staspidx
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
	ldy     #$20
	ldx     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	ldy     #$20
	sta     (sp),y
	pla
L00D2:	ldy     #$20
	lda     (sp),y
	jne     L00D0
	jmp     L00DB
L00D9:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L00E6
	inx
L00E6:	ldy     #$00
	jsr     ldauidx
	cmp     #$2E
	jsr     booleq
	jeq     L00E3
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
L00E3:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	ldy     #$25
	clc
	adc     (sp),y
	bcc     L00EC
	inx
L00EC:	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$23
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$23
	sta     (sp),y
	pla
	ldy     #$22
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$22
	sta     (sp),y
	pla
L00DB:	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L00DE
	inx
L00DE:	ldy     #$00
	jsr     ldauidx
	jeq     L00DF
	lda     sp
	ldx     sp+1
	ldy     #$23
	clc
	adc     (sp),y
	bcc     L00E1
	inx
L00E1:	ldy     #$00
	jsr     ldauidx
	cmp     #$45
	jsr     boolne
	jne     L00DC
L00DF:	ldx     #$00
	lda     #$00
	jeq     L00E2
L00DC:	ldx     #$00
	lda     #$01
L00E2:	jne     L00D9
L00DA:	ldy     #$29
	jsr     ldaxysp
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
L0069:	ldy     #$29
	jsr     ldaxysp
	jmp     L0022
L0022:	ldy     #$2A
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; unsigned long __near__ ffloor (unsigned long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ffloor: near

.segment	"CODE"

	jsr     pusheax
	jsr     decsp8
	ldy     #$0B
	jsr     ldeaxysp
	jsr     __ftoi
	jsr     axlong
	ldy     #$04
	jsr     steaxysp
	ldy     #$05
	jsr     ldaxysp
	jsr     __itof
	ldy     #$00
	jsr     steaxysp
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0F
	jsr     ldeaxysp
	jsr     __fcmp
	cmp     #$00
	jsr     booleq
	jne     L000E
	ldx     #$00
	lda     #$00
	jsr     __itof
	jsr     pusheax
	ldy     #$0F
	jsr     ldeaxysp
	jsr     __fcmp
	cmp     #$01
	jsr     booleq
	jne     L000E
	ldx     #$00
	lda     #$00
	jeq     L001B
L000E:	ldx     #$00
	lda     #$01
L001B:	jeq     L000D
	ldy     #$03
	jsr     ldeaxysp
	jmp     L0004
L000D:	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$01
	jsr     __fsub
	jmp     L0004
L0004:	ldy     #$0C
	jsr     addysp
	rts

.endproc

